spring:
  application:
    name: payment-service
  jpa:
    show-sql: true
  datasource:
    driver-class: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/alurafood-payment-service?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: secret;123!

server:
  port: 0
  servlet:
    context-path: /alura-food/api

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int}
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka

resilience4j:
  circuitbreaker:
    instances:
      confirmPayment:
        slidingWindowSize: 3
        minimumNumberOfCalls: 2
        waitDurationInOpenState: 50s